#!/bin/bash

swift --version
swift build -c release --product KrabbyPatty
mkdir -p main.artifactbundle/KrabbyPatty

cp .build/release/Modules/KrabbyPatty.swiftinterface main.artifactbundle/KrabbyPatty

for file in .build/release/*.{so,dylib}; do
    if [ -f $file ]; then
        cp $file main.artifactbundle/KrabbyPatty
    fi
done

(
cat <<EOF
{
    "schemaVersion": "1.2",
    "artifacts": {
        "KrabbyPatty": {
            "type": "library",
            "version": "$1",
            "variants": [{ "path": "KrabbyPatty" }]
        }
    }
}
EOF
) > main.artifactbundle/info.json
