#!/bin/bash
set -e

if [ -z $LIBRARY_PLATFORM ]; then
    echo "LIBRARY_PLATFORM environment variable not set"
    exit 1
fi

if [ -z $LIBRARY_VERSION ]; then
    echo "LIBRARY_VERSION environment variable not set"
    exit 1
fi

while [[ $# -gt 0 ]]; do
    aws s3 cp $1 \
        s3://tayloraswift/swift-edsl-example/$LIBRARY_VERSION/$LIBRARY_PLATFORM/$1 \
        --content-type application/zip
    shift
done
