name: package

on:
    workflow_dispatch:
    #   We build semver tags, and the master branch.
    push:
        branches: [ master ]
        tags:
            -   '[0-9]+.[0-9]+.[0-9]+'

jobs:
    macos:
        runs-on: macos-15
        name: macOS
        steps:
            -   name: Setup AWS CLI
                uses: aws-actions/configure-aws-credentials@v1
                with:
                    aws-secret-access-key: ${{ secrets.AWS_S3_ACCESS_SECRET }}
                    aws-access-key-id: ${{ vars.AWS_S3_ACCESS_KEY }}
                    aws-region: us-east-1

            -   name: Checkout repository
                uses: actions/checkout@v3

            -   name: Build artifacts
                run: Scripts/CreateArtifactBundle ${{ github.head_ref || github.ref_name }}

            -   name: Upload artifacts
                env:
                    LIBRARY_PLATFORM: "${{ runner.os }}-${{ runner.arch }}"
                    LIBRARY_VERSION: ${{ github.head_ref || github.ref_name }}

                run: Scripts/Deploy main.artifactbundle.zip

    linux:
        strategy:
            matrix:
                os:
                    -   codename: amazonlinux2
                        version: Amazon-Linux-2
                        display: Amazon Linux 2

                    -   codename: jammy
                        version: Ubuntu-22.04
                        display: Ubuntu 22.04

                    -   codename: noble
                        version: Ubuntu-24.04
                        display: Ubuntu 24.04
                arch:
                    -   id: x86_64
                        name: X64

        runs-on: ubuntu-24.04
        name: "${{ matrix.os.display }} (${{ matrix.arch.id }})"
        steps:
            -   name: Setup AWS CLI
                uses: aws-actions/configure-aws-credentials@v1
                with:
                    aws-secret-access-key: ${{ secrets.AWS_S3_ACCESS_SECRET }}
                    aws-access-key-id: ${{ vars.AWS_S3_ACCESS_KEY }}
                    aws-region: us-east-1

            -   name: Checkout repository
                uses: actions/checkout@v3

            -   name: Build artifacts
                run: |
                    docker run --rm \
                        -v $PWD:/package \
                        -w /package \
                        swift:6.0.3-${{ matrix.os.codename }} \
                        Scripts/CreateArtifactBundle ${{ github.head_ref || github.ref_name }}

            -   name: Upload artifacts
                env:
                    LIBRARY_PLATFORM: "${{ matrix.os.version }}-${{ matrix.arch.name }}"
                    LIBRARY_VERSION: ${{ github.head_ref || github.ref_name }}

                run: Scripts/Deploy main.artifactbundle.zip
